version: '3'

services:

  payload:
    image: node:18-alpine
    ports:
      - "4000:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "npm install && npm run dev"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/payload
      PORT: 3000
      NODE_ENV: development
      PAYLOAD_SECRET: TESTING
      S3_BUCKET: die-karte-payload-cms
      S3_ACCESS_KEY_ID: AKIA2RET2DDLTCC23YEJ
      S3_SECRET_ACCESS_KEY: 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
      S3_REGION: eu-central-1
      SERVER_URL: http://localhost:4000
      # PAYLOAD_SEED: "true"
      # PAYLOAD_DROP_DATABASE: "true"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  node_modules:
